// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAymZJXOGiAgpBr9iuV-xN9Lri5WANCGaM',
    appId: '1:143941870151:web:65db295bf01a1208d2c762',
    messagingSenderId: '143941870151',
    projectId: 'appstore-650b2',
    authDomain: 'appstore-650b2.firebaseapp.com',
    storageBucket: 'appstore-650b2.appspot.com',
    measurementId: 'G-4S71BPW0G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDXFNIn5PJuTFWqFRRx8ZXCV-Mm_KMhV0',
    appId: '1:143941870151:android:cea4adede5fbabddd2c762',
    messagingSenderId: '143941870151',
    projectId: 'appstore-650b2',
    storageBucket: 'appstore-650b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPho2jO8lDnAmM0-lkNtsQURHZBix5Ci0',
    appId: '1:143941870151:ios:135821ff290340d8d2c762',
    messagingSenderId: '143941870151',
    projectId: 'appstore-650b2',
    storageBucket: 'appstore-650b2.appspot.com',
    androidClientId: '143941870151-qpfjo3sl48785is2qm5r6sf6mtjvrqqg.apps.googleusercontent.com',
    iosClientId: '143941870151-itfm44vcmf2ar5catv7jd1p9btqvk8qs.apps.googleusercontent.com',
    iosBundleId: 'com.mounika.appstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPho2jO8lDnAmM0-lkNtsQURHZBix5Ci0',
    appId: '1:143941870151:ios:135821ff290340d8d2c762',
    messagingSenderId: '143941870151',
    projectId: 'appstore-650b2',
    storageBucket: 'appstore-650b2.appspot.com',
    androidClientId: '143941870151-qpfjo3sl48785is2qm5r6sf6mtjvrqqg.apps.googleusercontent.com',
    iosClientId: '143941870151-itfm44vcmf2ar5catv7jd1p9btqvk8qs.apps.googleusercontent.com',
    iosBundleId: 'com.mounika.appstore',
  );
}
